### ISSUE TITLE
Download-Folder has to be configurable

### ISSUE THREAD

**Issue by Stipci** [Qytera-Gmbh/QTAF#221]
Need a option to set up the download folder. On my wish it is a good option that the download is then setup to the local "target" or "log" folder.

**Comment by MoritzSalein** [comment]
Is this not the point that we should include in our configuation a general possibility for browser options? It is quite similar to the ticket of headless https://github.com/Qytera-Gmbh/QTAF/issues/175.

**Comment by qytera-development** [comment]
If you want to set the download folder you can already do that by overwriting the browser class. You clould also define a new key in the qtaf.json file, read it via the ConfigMap class and then set the value in the Driver class.

**Comment by OliverHoenig** [comment]
@qytera-development @MoritzSalein @Stipci Is this a feature we should continue to work on or is the workaround sufficient?

**Comment by MoritzSalein** [comment]
Currently we can't include a solution in our Framework. You have to follow the idea of qytera-development.
@OliverHoenig Please add an additional link to an external resource where you can find a desciption of overwriting a browser class. When the link is added, ticket can be closed.

**Comment by csvtuda** [comment]
Resolving this issue is not possible through basic driver options/capabilities. For Chromium-based browsers, [experimental options](https://stackoverflow.com/a/68558137) need to be defined. For Firefox, the [preferences](https://stackoverflow.com/a/36309735) need to be properly configured instead. For Internet Explorer, I do not really want to look it up.

**Comment by OliverHoenig** [comment]
A fix has been implemented in v0.2.20.
