### ISSUE TITLE
Browser open if only API tests are running

### ISSUE THREAD

**Issue by MoritzSalein** [Qytera-Gmbh/QTAF#267]
During the execution of API-only tests, the browser always appears shortly, which would not actually be necessary.

**Comment by OliverHoenig** [comment]
Thank you Moritz for reporting this.
The behaviour could be reproduced and does not correspond to the desired behaviour. If only tests are carried out for which the browser is not required, the browser should not be opened.
However, it should be noted that this behaviour does not hinder the execution of the tests, which is why this issue is assigned a low priority.
